### ISSUE TITLE
What are these tools for?

### ISSUE THREAD

**Issue by shirakaba** [bvschaik/citybuilding-tools#1]
I'm wondering whether these tools are for something like extracting image assets from the game data of Impressions games? If so, could you detail how to use them?

**Comment by bvschaik** [comment]
Sgreader is indeed a tool to extract images from the .sg2/.sg3 files that are present in the Impressions games citybuilders. Its use should be self-explanatory.

Engconverter is a tool to convert the binary .eng (language) files from the games to a more accessible XML format, and back again, allowing users to change the texts as they please.

I should probably write a proper readme one day 😉

**Comment by shirakaba** [comment]
> Sgreader is indeed a tool to extract images from the .sg2/.sg3 files that are present in the Impressions games citybuilders. Its use should be self-explanatory.

I see now that it's GUI-based, and some Windows releases are already provided. I'll have a play with it some time!
