### ISSUE TITLE
Could you please upload a release of sgreader?

### ISSUE THREAD

**Issue by shirakaba** [bvschaik/citybuilding-tools#2]
My only Windows device, a tablet PC, doesn't have enough space left to install an IDE to build sgreader (not to mention my minimal experience in C++); if it's no trouble, could you possibly produce a release? I'd like to explore the Emperor: Rise of the Middle Kingdom files.

**Comment by Morgan-Allen** [comment]
Do you have any experience with Java development?  I put together a version of SG_reader in java that should allow write-capabilities as well, though it doesn't have much of a GUI at the moment.

**Comment by shirakaba** [comment]
@Morgan-Allen There's an idea – I think my Windows tablet has a relatively recent Java VM installed. As far as I understand, one needs a Windows machine to build a Windows C++ program, but Java would mean I could just build it on my Mac and copy over to the tablet PC (I do have Java experience). Could you link me to your repo? And does your version of the app allow export to a more common file format like PNG/GIF?

**Comment by Morgan-Allen** [comment]
The repository should be available below.  (There's also a C++ equivalent-codebase included.)

https://github.com/Morgan-Allen/SG_Reader

Java generally allows read/write options for .jpg/.gif/.png formats, and you can google tutorials easily enough.  If you run into any roadblocks, give me a ping and see if I can remember any solutions.

EDIT:  Also, please note that this utility was developed for Caesar 3 and has not been tested with Emperor.  Bianca tells me the formats are similar, however, so it should at least be adaptable without too much pain.

**Comment by shirakaba** [comment]
Thank you! I'll try to get these set up.

**Comment by bvschaik** [comment]
I'll upload a release .exe this weekend, once I get my cross-compiler for Windows up-and-running again!

**Comment by bvschaik** [comment]
It took a little longer than expected, but here it is: https://github.com/bvschaik/citybuilding-tools/releases/tag/sgreader-v1.1
